context("Gadget data files")

expect_string <- function(actual, ...) {
    expect_equal(
        as.character(actual),
        paste0(c(...), "\n", collapse = ""))
}

test_that("Can generate gadgetfile objects", {
    expect_error(
        gadget_file(),
        "filename")

    expect_equal(
        class(gadget_file("wibble")),
        c("gadget_file"))
})

test_that("Can get a string representation", {
    expect_string(
        gadget_file("wobble", properties = list(
            cabbage = "yes",
            potatoes = c("1 potato", "2 potato", "3 potato", "4!"),
            sprouts = 'Like, "Eeeew!"')),
        paste("; Generated by mfdb", packageVersion("mfdb")),
        "cabbage\tyes",
        "potatoes\t1 potato\t2 potato\t3 potato\t4!",
        'sprouts\tLike, "Eeeew!"')
})

test_that("Can add components and preambles", {
    expect_string(
        gadget_file("wobble",
            properties = structure(list(sprouts = 'Like, "Eeeew!"'), preamble = "Carrots"),
            components = list(
                component = structure(list(name = "component1"), preamble = list("The first component", "I like it")),
                component = structure(list(name = "component2"), preamble = "The second component (with the same name)"),
                tea = structure(list(milk = 1, sugars = 2), preamble = "Tea, please"))
            ),
        paste("; Generated by mfdb", packageVersion("mfdb")),
        "; Carrots",
        'sprouts\tLike, "Eeeew!"',
        '; The first component',
        '; I like it',
        '[component]',
        'name\tcomponent1',
        '; The second component (with the same name)',
        '[component]',
        'name\tcomponent2',
        '; Tea, please',
        '[tea]',
        'milk\t1',
        'sugars\t2')
})

test_that("Can include tabular data", {
    expect_string(
        gadget_file("wobble",
            data = data.frame(a = c(1,3), b = c(2,5))),
        paste("; Generated by mfdb", packageVersion("mfdb")),
        "; -- data --",
        "; a\tb",
        "1\t2",
        "3\t5")
})
