context("Gadget data files")

expect_string <- function(actual, ...) {
    expect_equal(strsplit(as.character(actual), "\n"), list(...))
}

test_that("Can generate gadgefile objects", {
    expect_error(
        gadget_file(),
        "filename")

    expect_equal(
        class(gadget_file("wibble")),
        c("gadget_file"))
})

test_that("Can get a string representation", {
    expect_string(
        gadget_file("wobble", properties = list(
            cabbage = "yes",
            potatoes = c("1 potato", "2 potato", "3 potato", "4!"),
            sprouts = 'Like, "Eeeew!"')),
        paste("; Generated by mfdb", packageVersion("mfdb")),
        "cabbage\tyes",
        "potatoes\t1 potato\t2 potato\t3 potato\t4!",
        'sprouts\tLike, "Eeeew!"')
})

test_that("Can add components and preambles", {
    expect_string(
        gadget_file("wobble",
            properties = list(
                preamble = "Carrots",
                sprouts = 'Like, "Eeeew!"'),
            components = list(
                component = list(preamble = c("The first component", "I like it"), name = "component1"),
                component = list(preamble = "The second component (with the same name)", name = "component2"),
                tea = list(preamble = "Tea, please", milk = 1, sugars = 2))
            ),
        paste("; Generated by mfdb", packageVersion("mfdb")),
        "; Carrots",
        'sprouts\tLike, "Eeeew!"',
        '; The first component',
        '; I like it',
        '[component]',
        'name\tcomponent1',
        '; The second component (with the same name)',
        '[component]',
        'name\tcomponent2',
        '; Tea, please',
        '[tea]',
        'milk\t1',
        'sugars\t2')
})

test_that("Can include tabular data", {
    expect_string(
        gadget_file("wobble",
            data = data.frame(a = c(1,3), b = c(2,5))),
        paste("; Generated by mfdb", packageVersion("mfdb")),
        "; -- data --",
        "; a\tb",
        "1\t2",
        "3\t5")
})
