gadget_file <- function (filename, properties = list(), components = list(), data_preamble = NULL, data = NULL) {
    properties$preamble <- c(list(
        paste("Generated by mfdb", packageVersion("mfdb"))), properties$preamble)
    structure(list(
        filename = filename,
        components = c(list(as.list(properties)), as.list(components)),
        data_preamble = as.list(data_preamble),
        data = data), class = "gadget_file")
}

# Print character representation of the gadget file to stdout
print.gadget_file <- function (x, ...) {
    print_component <- function (comp, name) {
        # Print all preambles as comments
        cat("; ")
        cat(paste(as.list(comp$preamble), collapse = "\n; "))
        cat("\n")

        if (is.character(name) && nzchar(name)) cat(paste0('[', name,']\n'))

        # properties are in key\tvalue1\tvalue2... form
        for (k in names(comp)) {
            if (!(k %in% c("preamble"))) {
                cat(paste0(k, "\t", paste(comp[[k]], collapse = "\t"), "\n"))
            }
        }
    }

    if (length(x$components) > 0) {
        for (i in 1:length(x$components)) print_component(
            x$components[[i]],
            names(x$components)[[i]])
    }

    if (!is.null(x$data)) {
        if (length(x$data_preamble) > 0) {
            cat(paste0("; ", x$data_preamble, "\n"))
        }
        cat("; -- data --\n; ")
        write.table(x$data,
                file = "",
                quote = FALSE,
                sep = "\t",
                col.names = TRUE,
                row.names = FALSE,
                fileEncoding = "utf-8")
    }
}

# Return a character representation of the gadget file
as.character.gadget_file <- function (x, ...) {
    capture.output(print.gadget_file(x))
}

# Load gadget file into memory
read.gadget_file <- function(file_name, fileEncoding = "UTF-8") {
    extract <- function (pattern, line) {
        m <- regmatches(line, regexec(pattern, line))[[1]]
        if (length(m) > 1) m[2:length(m)] else c()
    }

    file <- file(file_name, "rt", encoding = fileEncoding)
    on.exit(close(file))

    properties <- list()
    components <- list(list())
    data_preamble <- NULL
    data <- NULL
    comp_name <- NULL
    cur_comp <- list()
    cur_preamble <- list()
    while(TRUE) {
        line <- readLines(file, n = 1)
        # Got to end of file, stop here
        if (length(line) == 0) {
            if(is.null(comp_name)) properties <- cur_comp else components[[comp_name]] <- cur_comp
            break
        }

        # Ignore version preamble, since this will be replaced on output
        if (length(grep("^; Generated by mfdb", line)) > 0) {
            next
        }

        # Switching to data mode
        if (length(grep("^; -- data --$", line)) > 0) {
            if(is.null(comp_name)) properties <- cur_comp else components[[comp_name]] <- cur_comp
            data_preamble <- cur_preamble
            header <- strsplit(readLines(file, n = 1), "\\s")[[1]]
            if(length(header) < 2) stop(paste("Not enough parts in data header", header))
            # TODO: error-check header
            data <- read.table(file,
                header=FALSE,
                quote = "",
                sep = "\t",
                col.names = header[2:length(header)],
                fileEncoding = "utf-8")
            break
        }

        # Add any comments as a preamble
        x <- extract("^;\\s*(.*)", line)
        if (length(x) > 0) {
            # Ignore any initial blank comments
            if(length(cur_preamble) > 0 || nchar(x[[1]]) > 0) {
                cur_preamble <- c(cur_preamble, list(x[[1]]))
            }
            next
        }

        # Start of new component
        x <- extract("^\\[(\\w+)\\]", line)
        if (length(x) > 0) {
            if(is.null(comp_name)) properties <- cur_comp else components[[comp_name]] <- cur_comp
            comp_name <- x[[1]]
            cur_comp <- list()
            next
        }

        # Any other line shoud be a \t seperated list
        x <- unlist(strsplit(line, "\t"))
        if (length(x) > 0) {
            # Started writing items, so must have got to the end of the preamble
            if (length(cur_preamble) > 0) {
                cur_comp$preamble <- cur_preamble
                cur_preamble <- list()
            }
            cur_comp[[x[[1]]]] <- if (length(x) > 1) x[2:length(x)] else ""
            next
        }
    }
    gadget_file(file_name, properties = properties, components = components, data_preamble = data_preamble, data = data)
}
